/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.3.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDateTimeEdit>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLayout>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTabWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QToolBox>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralWidget;
    QGroupBox *groupBox;
    QTextEdit *textEdit;
    QPushButton *homeButton;
    QPushButton *user_Button;
    QPushButton *collectionButton;
    QPushButton *messageButton;
    QPushButton *pushButton_recharge;
    QLabel *label_message_2;
    QLabel *label_money;
    QLabel *label_home;
    QLabel *label_data;
    QLabel *label_collection;
    QLabel *label_message;
    QGroupBox *groupBox_2;
    QLabel *label_location;
    QToolBox *toolBox;
    QWidget *page1;
    QPushButton *ncgc_Button;
    QLabel *xian;
    QLabel *xian_2;
    QPushButton *jxnu_Button;
    QPushButton *jxnu_Button_2;
    QPushButton *jxnu_Button_3;
    QWidget *page2;
    QWidget *page3;
    QWidget *page_back;
    QDateTimeEdit *dateTimeEdit;
    QTabWidget *tabWidget_jxnu;
    QWidget *tab;
    QLabel *xian_3;
    QLabel *xian_4;
    QLabel *xian_5;
    QLabel *xian_6;
    QLabel *label;
    QPushButton *pushButton_2;
    QPushButton *pushButton_3;
    QPushButton *pushButton_4;
    QPushButton *pushButton_5;
    QPushButton *pushButton_6;
    QGroupBox *groupBox_11;
    QGroupBox *groupBox_3;
    QLabel *label_food1;
    QLabel *label_desc;
    QLabel *label_value;
    QPushButton *pushButton_get;
    QGroupBox *groupBox_4;
    QLabel *label_food1_2;
    QLabel *label_desc_2;
    QLabel *label_value_2;
    QPushButton *pushButton_get_2;
    QGroupBox *groupBox_7;
    QLabel *label_food1_5;
    QLabel *label_desc_5;
    QLabel *label_value_5;
    QPushButton *pushButton_get_5;
    QGroupBox *groupBox_8;
    QLabel *label_food1_6;
    QLabel *label_desc_6;
    QLabel *label_value_6;
    QPushButton *pushButton_get_6;
    QPushButton *pushButton_get_7;
    QGroupBox *groupBox_9;
    QLabel *label_food1_7;
    QLabel *label_desc_7;
    QLabel *label_value_7;
    QPushButton *pushButton_get_8;
    QGroupBox *groupBox_10;
    QLabel *label_food1_8;
    QLabel *label_desc_8;
    QLabel *label_value_8;
    QPushButton *pushButton_get_9;
    QGroupBox *groupBox_5;
    QLabel *label_food1_3;
    QLabel *label_desc_3;
    QLabel *label_value_3;
    QPushButton *pushButton_get_3;
    QGroupBox *groupBox_6;
    QLabel *label_food1_4;
    QLabel *label_desc_4;
    QLabel *label_value_4;
    QPushButton *pushButton_get_4;
    QGroupBox *groupBox_12;
    QGroupBox *groupBox_13;
    QLabel *label_food1_9;
    QLabel *label_desc_9;
    QLabel *label_value_9;
    QPushButton *pushButton_get_10;
    QGroupBox *groupBox_14;
    QLabel *label_food1_10;
    QLabel *label_desc_10;
    QLabel *label_value_10;
    QPushButton *pushButton_get_11;
    QGroupBox *groupBox_15;
    QLabel *label_food1_11;
    QLabel *label_desc_11;
    QLabel *label_value_11;
    QPushButton *pushButton_get_14;
    QGroupBox *groupBox_16;
    QLabel *label_food1_12;
    QLabel *label_desc_12;
    QLabel *label_value_12;
    QPushButton *pushButton_get_15;
    QGroupBox *groupBox_17;
    QLabel *label_food1_13;
    QLabel *label_desc_13;
    QLabel *label_value_13;
    QPushButton *pushButton_get_16;
    QGroupBox *groupBox_18;
    QLabel *label_food1_14;
    QLabel *label_desc_14;
    QLabel *label_value_14;
    QPushButton *pushButton_get_17;
    QGroupBox *groupBox_19;
    QLabel *label_food1_15;
    QLabel *label_desc_15;
    QLabel *label_value_15;
    QPushButton *pushButton_get_12;
    QGroupBox *groupBox_20;
    QLabel *label_food1_16;
    QLabel *label_desc_16;
    QLabel *label_value_16;
    QPushButton *pushButton_get_13;
    QGroupBox *groupBox_21;
    QLabel *label_food1_17;
    QLabel *label_desc_17;
    QLabel *label_value_17;
    QPushButton *pushButton_get_18;
    QGroupBox *groupBox_22;
    QLabel *label_food1_18;
    QLabel *label_desc_18;
    QLabel *label_value_18;
    QPushButton *pushButton_get_19;
    QGroupBox *groupBox_23;
    QLabel *label_food1_20;
    QLabel *label_desc_20;
    QLabel *label_value_20;
    QPushButton *pushButton_get_20;
    QGroupBox *groupBox_24;
    QLabel *label_food1_22;
    QLabel *label_desc_22;
    QLabel *label_value_22;
    QPushButton *pushButton_get_21;
    QPushButton *pushButton;
    QWidget *tab_2;
    QGroupBox *groupBox_hold;
    QLabel *label_hold;
    QPushButton *pushButton_create;
    QPushButton *pushButton_admin;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(1355, 767);
        MainWindow->setStyleSheet(QStringLiteral("background-image: url(:/pic_main/back_new.jpg);"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        centralWidget->setStyleSheet(QStringLiteral(""));
        groupBox = new QGroupBox(centralWidget);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(0, -10, 1351, 131));
        groupBox->setStyleSheet(QStringLiteral(""));
        textEdit = new QTextEdit(groupBox);
        textEdit->setObjectName(QStringLiteral("textEdit"));
        textEdit->setGeometry(QRect(10, 10, 311, 101));
        textEdit->setStyleSheet(QStringLiteral("color: rgb(0, 0, 0);"));
        textEdit->setReadOnly(true);
        homeButton = new QPushButton(groupBox);
        homeButton->setObjectName(QStringLiteral("homeButton"));
        homeButton->setGeometry(QRect(500, 0, 151, 81));
        homeButton->setCursor(QCursor(Qt::PointingHandCursor));
        homeButton->setStyleSheet(QStringLiteral("border-image: url(:/pic_main/home.png);"));
        user_Button = new QPushButton(groupBox);
        user_Button->setObjectName(QStringLiteral("user_Button"));
        user_Button->setGeometry(QRect(670, 0, 151, 81));
        user_Button->setCursor(QCursor(Qt::PointingHandCursor));
        user_Button->setStyleSheet(QStringLiteral("border-image: url(:/pic_main/user_more.png);"));
        collectionButton = new QPushButton(groupBox);
        collectionButton->setObjectName(QStringLiteral("collectionButton"));
        collectionButton->setGeometry(QRect(840, 0, 151, 81));
        collectionButton->setCursor(QCursor(Qt::PointingHandCursor));
        collectionButton->setStyleSheet(QStringLiteral("border-image: url(:/pic_main/favorite.png);"));
        messageButton = new QPushButton(groupBox);
        messageButton->setObjectName(QStringLiteral("messageButton"));
        messageButton->setGeometry(QRect(1010, 0, 151, 81));
        messageButton->setCursor(QCursor(Qt::PointingHandCursor));
        messageButton->setStyleSheet(QStringLiteral("border-image: url(:/pic_main/comment.net.png);"));
        pushButton_recharge = new QPushButton(groupBox);
        pushButton_recharge->setObjectName(QStringLiteral("pushButton_recharge"));
        pushButton_recharge->setGeometry(QRect(1260, 20, 93, 61));
        QFont font;
        font.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font.setPointSize(18);
        font.setBold(false);
        font.setWeight(50);
        pushButton_recharge->setFont(font);
        pushButton_recharge->setStyleSheet(QStringLiteral("image: url(:/pic_main/111.png);"));
        label_message_2 = new QLabel(groupBox);
        label_message_2->setObjectName(QStringLiteral("label_message_2"));
        label_message_2->setGeometry(QRect(1170, 90, 71, 41));
        QFont font1;
        font1.setFamily(QString::fromUtf8("\345\215\216\346\226\207\351\232\266\344\271\246"));
        font1.setPointSize(20);
        label_message_2->setFont(font1);
        label_money = new QLabel(groupBox);
        label_money->setObjectName(QStringLiteral("label_money"));
        label_money->setGeometry(QRect(1170, 40, 111, 31));
        label_home = new QLabel(centralWidget);
        label_home->setObjectName(QStringLiteral("label_home"));
        label_home->setGeometry(QRect(540, 80, 71, 41));
        label_home->setFont(font1);
        label_data = new QLabel(centralWidget);
        label_data->setObjectName(QStringLiteral("label_data"));
        label_data->setGeometry(QRect(680, 80, 141, 41));
        label_data->setFont(font1);
        label_collection = new QLabel(centralWidget);
        label_collection->setObjectName(QStringLiteral("label_collection"));
        label_collection->setGeometry(QRect(870, 80, 101, 41));
        label_collection->setFont(font1);
        label_message = new QLabel(centralWidget);
        label_message->setObjectName(QStringLiteral("label_message"));
        label_message->setGeometry(QRect(1050, 80, 71, 41));
        label_message->setFont(font1);
        groupBox_2 = new QGroupBox(centralWidget);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(0, 120, 1351, 631));
        label_location = new QLabel(groupBox_2);
        label_location->setObjectName(QStringLiteral("label_location"));
        label_location->setGeometry(QRect(10, 70, 72, 61));
        label_location->setStyleSheet(QStringLiteral("image: url(:/pic_main/location.png);"));
        toolBox = new QToolBox(groupBox_2);
        toolBox->setObjectName(QStringLiteral("toolBox"));
        toolBox->setEnabled(true);
        toolBox->setGeometry(QRect(110, 50, 190, 311));
        QFont font2;
        font2.setFamily(QString::fromUtf8("\345\271\274\345\234\206"));
        font2.setPointSize(11);
        toolBox->setFont(font2);
        toolBox->setStyleSheet(QStringLiteral(""));
        page1 = new QWidget();
        page1->setObjectName(QStringLiteral("page1"));
        page1->setGeometry(QRect(0, 0, 190, 187));
        page1->setMinimumSize(QSize(190, 0));
        page1->setContextMenuPolicy(Qt::DefaultContextMenu);
        page1->setLayoutDirection(Qt::LeftToRight);
        page1->setStyleSheet(QStringLiteral("border-image: url(:/pic_main/weather.png);"));
        ncgc_Button = new QPushButton(page1);
        ncgc_Button->setObjectName(QStringLiteral("ncgc_Button"));
        ncgc_Button->setEnabled(true);
        ncgc_Button->setGeometry(QRect(100, 0, 90, 90));
        ncgc_Button->setCursor(QCursor(Qt::PointingHandCursor));
        ncgc_Button->setStyleSheet(QStringLiteral("image: url(:/pic_toolBox/hn2.jpg);"));
        xian = new QLabel(page1);
        xian->setObjectName(QStringLiteral("xian"));
        xian->setGeometry(QRect(0, 90, 200, 10));
        xian->setStyleSheet(QStringLiteral("border-image: url(:/pic_toolBox/string.png);"));
        xian_2 = new QLabel(page1);
        xian_2->setObjectName(QStringLiteral("xian_2"));
        xian_2->setGeometry(QRect(90, 0, 10, 191));
        xian_2->setStyleSheet(QStringLiteral("border-image: url(:/pic_toolBox/string.png);"));
        jxnu_Button = new QPushButton(page1);
        jxnu_Button->setObjectName(QStringLiteral("jxnu_Button"));
        jxnu_Button->setGeometry(QRect(0, 0, 90, 90));
        jxnu_Button->setCursor(QCursor(Qt::PointingHandCursor));
        jxnu_Button->setStyleSheet(QStringLiteral("image: url(:/pic_toolBox/hn1.jpg);"));
        jxnu_Button_2 = new QPushButton(page1);
        jxnu_Button_2->setObjectName(QStringLiteral("jxnu_Button_2"));
        jxnu_Button_2->setGeometry(QRect(0, 100, 90, 90));
        jxnu_Button_2->setCursor(QCursor(Qt::PointingHandCursor));
        jxnu_Button_2->setStyleSheet(QStringLiteral("image: url(:/pic_toolBox/4.png);"));
        jxnu_Button_3 = new QPushButton(page1);
        jxnu_Button_3->setObjectName(QStringLiteral("jxnu_Button_3"));
        jxnu_Button_3->setGeometry(QRect(100, 100, 90, 90));
        jxnu_Button_3->setCursor(QCursor(Qt::PointingHandCursor));
        jxnu_Button_3->setStyleSheet(QStringLiteral("image: url(:/pic_toolBox/5.png);"));
        QIcon icon;
        icon.addFile(QStringLiteral(":/pic_main/location_2.png"), QSize(), QIcon::Normal, QIcon::Off);
        icon.addFile(QStringLiteral(":/pic_main/location_off.png"), QSize(), QIcon::Disabled, QIcon::Off);
        icon.addFile(QStringLiteral(":/pic_main/location_off.png"), QSize(), QIcon::Disabled, QIcon::On);
        icon.addFile(QStringLiteral(":/pic_main/location_off.png"), QSize(), QIcon::Active, QIcon::Off);
        toolBox->addItem(page1, icon, QString::fromUtf8("\345\215\227\346\230\214\345\234\260\345\214\272(\344\270\234\357\274\211"));
        page2 = new QWidget();
        page2->setObjectName(QStringLiteral("page2"));
        page2->setGeometry(QRect(0, 0, 190, 187));
        page2->setStyleSheet(QStringLiteral("border-image: url(:/pic_main/weather.png);"));
        toolBox->addItem(page2, QStringLiteral(""));
        page3 = new QWidget();
        page3->setObjectName(QStringLiteral("page3"));
        page3->setGeometry(QRect(0, 0, 190, 187));
        page3->setStyleSheet(QStringLiteral("border-image: url(:/pic_main/weather.png);"));
        toolBox->addItem(page3, QStringLiteral(""));
        page_back = new QWidget();
        page_back->setObjectName(QStringLiteral("page_back"));
        page_back->setGeometry(QRect(0, 0, 190, 187));
        toolBox->addItem(page_back, QStringLiteral(""));
        dateTimeEdit = new QDateTimeEdit(groupBox_2);
        dateTimeEdit->setObjectName(QStringLiteral("dateTimeEdit"));
        dateTimeEdit->setEnabled(true);
        dateTimeEdit->setGeometry(QRect(1220, 590, 194, 22));
        dateTimeEdit->setInputMethodHints(Qt::ImhPreferNumbers);
        dateTimeEdit->setReadOnly(true);
        tabWidget_jxnu = new QTabWidget(groupBox_2);
        tabWidget_jxnu->setObjectName(QStringLiteral("tabWidget_jxnu"));
        tabWidget_jxnu->setGeometry(QRect(300, 10, 1051, 576));
        tabWidget_jxnu->setStyleSheet(QStringLiteral(""));
        tabWidget_jxnu->setIconSize(QSize(48, 48));
        tab = new QWidget();
        tab->setObjectName(QStringLiteral("tab"));
        tab->setStyleSheet(QStringLiteral(""));
        xian_3 = new QLabel(tab);
        xian_3->setObjectName(QStringLiteral("xian_3"));
        xian_3->setGeometry(QRect(0, 0, 1501, 10));
        xian_3->setStyleSheet(QStringLiteral("border-image: url(:/pic_toolBox/string.png);"));
        xian_4 = new QLabel(tab);
        xian_4->setObjectName(QStringLiteral("xian_4"));
        xian_4->setGeometry(QRect(0, 0, 10, 523));
        xian_4->setStyleSheet(QStringLiteral("border-image: url(:/pic_toolBox/string.png);"));
        xian_5 = new QLabel(tab);
        xian_5->setObjectName(QStringLiteral("xian_5"));
        xian_5->setGeometry(QRect(0, 510, 1051, 10));
        xian_5->setStyleSheet(QStringLiteral("border-image: url(:/pic_toolBox/string.png);"));
        xian_6 = new QLabel(tab);
        xian_6->setObjectName(QStringLiteral("xian_6"));
        xian_6->setGeometry(QRect(1040, 0, 10, 523));
        xian_6->setStyleSheet(QStringLiteral("border-image: url(:/pic_toolBox/string.png);"));
        label = new QLabel(tab);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(120, 10, 10, 501));
        label->setStyleSheet(QStringLiteral("border-image: url(:/pic_toolBox/string.png);"));
        pushButton_2 = new QPushButton(tab);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(10, 10, 110, 51));
        QFont font3;
        font3.setFamily(QString::fromUtf8("\346\245\267\344\275\223"));
        font3.setPointSize(14);
        pushButton_2->setFont(font3);
        pushButton_2->setStyleSheet(QLatin1String("border-image: url(:/pic_main/25.jpg);\n"
"image: url(:/pic_tabBox/Spaghetti.png);"));
        pushButton_3 = new QPushButton(tab);
        pushButton_3->setObjectName(QStringLiteral("pushButton_3"));
        pushButton_3->setGeometry(QRect(10, 60, 110, 51));
        pushButton_3->setFont(font3);
        pushButton_3->setStyleSheet(QLatin1String("border-image: url(:/pic_main/25.jpg);\n"
"image: url(:/pic_tabBox/Chili Pepper.png);"));
        pushButton_4 = new QPushButton(tab);
        pushButton_4->setObjectName(QStringLiteral("pushButton_4"));
        pushButton_4->setGeometry(QRect(10, 110, 110, 51));
        pushButton_4->setFont(font3);
        pushButton_4->setStyleSheet(QLatin1String("border-image: url(:/pic_main/25.jpg);\n"
"image: url(:/pic_tabBox/French Fries.png);"));
        pushButton_5 = new QPushButton(tab);
        pushButton_5->setObjectName(QStringLiteral("pushButton_5"));
        pushButton_5->setGeometry(QRect(10, 160, 110, 51));
        pushButton_5->setFont(font3);
        pushButton_5->setStyleSheet(QLatin1String("border-image: url(:/pic_main/25.jpg);\n"
"image: url(:/pic_tabBox/Sushi.png);"));
        pushButton_6 = new QPushButton(tab);
        pushButton_6->setObjectName(QStringLiteral("pushButton_6"));
        pushButton_6->setGeometry(QRect(10, 210, 110, 51));
        pushButton_6->setFont(font3);
        pushButton_6->setStyleSheet(QLatin1String("border-image: url(:/pic_main/25.jpg);\n"
"image: url(:/pic_tabBox/Wine.png);"));
        groupBox_11 = new QGroupBox(tab);
        groupBox_11->setObjectName(QStringLiteral("groupBox_11"));
        groupBox_11->setGeometry(QRect(130, 20, 901, 331));
        groupBox_3 = new QGroupBox(groupBox_11);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(10, 0, 180, 130));
        label_food1 = new QLabel(groupBox_3);
        label_food1->setObjectName(QStringLiteral("label_food1"));
        label_food1->setGeometry(QRect(0, 0, 120, 80));
        label_food1->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/xiangtianwang.jpg);"));
        label_desc = new QLabel(groupBox_3);
        label_desc->setObjectName(QStringLiteral("label_desc"));
        label_desc->setGeometry(QRect(10, 90, 161, 16));
        QFont font4;
        font4.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font4.setBold(true);
        font4.setWeight(75);
        label_desc->setFont(font4);
        label_value = new QLabel(groupBox_3);
        label_value->setObjectName(QStringLiteral("label_value"));
        label_value->setGeometry(QRect(10, 110, 41, 16));
        QFont font5;
        font5.setFamily(QString::fromUtf8("\347\255\211\347\272\277"));
        font5.setPointSize(12);
        font5.setBold(true);
        font5.setWeight(75);
        label_value->setFont(font5);
        pushButton_get = new QPushButton(groupBox_3);
        pushButton_get->setObjectName(QStringLiteral("pushButton_get"));
        pushButton_get->setGeometry(QRect(120, 20, 61, 41));
        pushButton_get->setCursor(QCursor(Qt::OpenHandCursor));
        pushButton_get->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/1.jpg);"));
        groupBox_4 = new QGroupBox(groupBox_11);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(230, 0, 180, 130));
        label_food1_2 = new QLabel(groupBox_4);
        label_food1_2->setObjectName(QStringLiteral("label_food1_2"));
        label_food1_2->setGeometry(QRect(0, 0, 120, 80));
        label_food1_2->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/jirouchang.jpg);"));
        label_desc_2 = new QLabel(groupBox_4);
        label_desc_2->setObjectName(QStringLiteral("label_desc_2"));
        label_desc_2->setGeometry(QRect(10, 90, 161, 16));
        label_desc_2->setFont(font4);
        label_value_2 = new QLabel(groupBox_4);
        label_value_2->setObjectName(QStringLiteral("label_value_2"));
        label_value_2->setGeometry(QRect(10, 110, 41, 16));
        label_value_2->setFont(font5);
        pushButton_get_2 = new QPushButton(groupBox_4);
        pushButton_get_2->setObjectName(QStringLiteral("pushButton_get_2"));
        pushButton_get_2->setGeometry(QRect(120, 20, 61, 41));
        pushButton_get_2->setCursor(QCursor(Qt::OpenHandCursor));
        pushButton_get_2->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/1.jpg);"));
        groupBox_7 = new QGroupBox(groupBox_11);
        groupBox_7->setObjectName(QStringLiteral("groupBox_7"));
        groupBox_7->setGeometry(QRect(10, 160, 180, 130));
        label_food1_5 = new QLabel(groupBox_7);
        label_food1_5->setObjectName(QStringLiteral("label_food1_5"));
        label_food1_5->setGeometry(QRect(0, 0, 120, 80));
        label_food1_5->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/moxigelaweidianxinmian.jpg);"));
        label_desc_5 = new QLabel(groupBox_7);
        label_desc_5->setObjectName(QStringLiteral("label_desc_5"));
        label_desc_5->setGeometry(QRect(10, 90, 161, 16));
        label_desc_5->setFont(font4);
        label_value_5 = new QLabel(groupBox_7);
        label_value_5->setObjectName(QStringLiteral("label_value_5"));
        label_value_5->setGeometry(QRect(10, 110, 41, 16));
        label_value_5->setFont(font5);
        pushButton_get_5 = new QPushButton(groupBox_7);
        pushButton_get_5->setObjectName(QStringLiteral("pushButton_get_5"));
        pushButton_get_5->setGeometry(QRect(120, 20, 61, 41));
        pushButton_get_5->setCursor(QCursor(Qt::OpenHandCursor));
        pushButton_get_5->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/1.jpg);"));
        groupBox_8 = new QGroupBox(groupBox_11);
        groupBox_8->setObjectName(QStringLiteral("groupBox_8"));
        groupBox_8->setGeometry(QRect(230, 160, 180, 130));
        label_food1_6 = new QLabel(groupBox_8);
        label_food1_6->setObjectName(QStringLiteral("label_food1_6"));
        label_food1_6->setGeometry(QRect(0, 0, 120, 80));
        label_food1_6->setStyleSheet(QLatin1String("image: url(:/pic_tabBox/11S204/daliyuanheimi.JPEG);\n"
""));
        label_desc_6 = new QLabel(groupBox_8);
        label_desc_6->setObjectName(QStringLiteral("label_desc_6"));
        label_desc_6->setGeometry(QRect(10, 90, 161, 16));
        label_desc_6->setFont(font4);
        label_value_6 = new QLabel(groupBox_8);
        label_value_6->setObjectName(QStringLiteral("label_value_6"));
        label_value_6->setGeometry(QRect(10, 110, 41, 16));
        label_value_6->setFont(font5);
        pushButton_get_6 = new QPushButton(groupBox_8);
        pushButton_get_6->setObjectName(QStringLiteral("pushButton_get_6"));
        pushButton_get_6->setGeometry(QRect(170, 120, 61, 41));
        pushButton_get_6->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/1.jpg);"));
        pushButton_get_7 = new QPushButton(groupBox_8);
        pushButton_get_7->setObjectName(QStringLiteral("pushButton_get_7"));
        pushButton_get_7->setGeometry(QRect(120, 20, 61, 41));
        pushButton_get_7->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/1.jpg);"));
        groupBox_9 = new QGroupBox(groupBox_11);
        groupBox_9->setObjectName(QStringLiteral("groupBox_9"));
        groupBox_9->setGeometry(QRect(450, 160, 180, 130));
        label_food1_7 = new QLabel(groupBox_9);
        label_food1_7->setObjectName(QStringLiteral("label_food1_7"));
        label_food1_7->setGeometry(QRect(0, 0, 120, 80));
        label_food1_7->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/daliyuanyouyican.jpg);"));
        label_desc_7 = new QLabel(groupBox_9);
        label_desc_7->setObjectName(QStringLiteral("label_desc_7"));
        label_desc_7->setGeometry(QRect(10, 90, 161, 16));
        label_desc_7->setFont(font4);
        label_value_7 = new QLabel(groupBox_9);
        label_value_7->setObjectName(QStringLiteral("label_value_7"));
        label_value_7->setGeometry(QRect(10, 110, 41, 16));
        label_value_7->setFont(font5);
        pushButton_get_8 = new QPushButton(groupBox_9);
        pushButton_get_8->setObjectName(QStringLiteral("pushButton_get_8"));
        pushButton_get_8->setGeometry(QRect(130, 20, 61, 41));
        pushButton_get_8->setCursor(QCursor(Qt::OpenHandCursor));
        pushButton_get_8->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/1.jpg);"));
        groupBox_10 = new QGroupBox(groupBox_11);
        groupBox_10->setObjectName(QStringLiteral("groupBox_10"));
        groupBox_10->setGeometry(QRect(680, 160, 180, 130));
        label_food1_8 = new QLabel(groupBox_10);
        label_food1_8->setObjectName(QStringLiteral("label_food1_8"));
        label_food1_8->setGeometry(QRect(0, 0, 120, 80));
        label_food1_8->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/xizhilangyoulemeixaingyu.jpg);"));
        label_desc_8 = new QLabel(groupBox_10);
        label_desc_8->setObjectName(QStringLiteral("label_desc_8"));
        label_desc_8->setGeometry(QRect(10, 90, 161, 16));
        label_desc_8->setFont(font4);
        label_value_8 = new QLabel(groupBox_10);
        label_value_8->setObjectName(QStringLiteral("label_value_8"));
        label_value_8->setGeometry(QRect(10, 110, 41, 16));
        label_value_8->setFont(font5);
        pushButton_get_9 = new QPushButton(groupBox_10);
        pushButton_get_9->setObjectName(QStringLiteral("pushButton_get_9"));
        pushButton_get_9->setGeometry(QRect(130, 20, 61, 41));
        pushButton_get_9->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_get_9->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/1.jpg);"));
        groupBox_5 = new QGroupBox(groupBox_11);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(450, 0, 180, 130));
        label_food1_3 = new QLabel(groupBox_5);
        label_food1_3->setObjectName(QStringLiteral("label_food1_3"));
        label_food1_3->setGeometry(QRect(0, 0, 120, 80));
        label_food1_3->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/kangshifulaotan.jpg);"));
        label_desc_3 = new QLabel(groupBox_5);
        label_desc_3->setObjectName(QStringLiteral("label_desc_3"));
        label_desc_3->setGeometry(QRect(10, 90, 161, 16));
        label_desc_3->setFont(font4);
        label_value_3 = new QLabel(groupBox_5);
        label_value_3->setObjectName(QStringLiteral("label_value_3"));
        label_value_3->setGeometry(QRect(10, 110, 41, 16));
        label_value_3->setFont(font5);
        pushButton_get_3 = new QPushButton(groupBox_5);
        pushButton_get_3->setObjectName(QStringLiteral("pushButton_get_3"));
        pushButton_get_3->setGeometry(QRect(130, 20, 61, 41));
        pushButton_get_3->setCursor(QCursor(Qt::OpenHandCursor));
        pushButton_get_3->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/1.jpg);"));
        groupBox_6 = new QGroupBox(groupBox_11);
        groupBox_6->setObjectName(QStringLiteral("groupBox_6"));
        groupBox_6->setGeometry(QRect(680, 0, 180, 130));
        label_food1_4 = new QLabel(groupBox_6);
        label_food1_4->setObjectName(QStringLiteral("label_food1_4"));
        label_food1_4->setGeometry(QRect(0, 0, 120, 80));
        label_food1_4->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/xianglaniuroumian.jpg);"));
        label_desc_4 = new QLabel(groupBox_6);
        label_desc_4->setObjectName(QStringLiteral("label_desc_4"));
        label_desc_4->setGeometry(QRect(10, 90, 161, 16));
        label_desc_4->setFont(font4);
        label_value_4 = new QLabel(groupBox_6);
        label_value_4->setObjectName(QStringLiteral("label_value_4"));
        label_value_4->setGeometry(QRect(10, 110, 41, 16));
        label_value_4->setFont(font5);
        pushButton_get_4 = new QPushButton(groupBox_6);
        pushButton_get_4->setObjectName(QStringLiteral("pushButton_get_4"));
        pushButton_get_4->setGeometry(QRect(130, 20, 61, 41));
        pushButton_get_4->setCursor(QCursor(Qt::OpenHandCursor));
        pushButton_get_4->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/1.jpg);"));
        groupBox_10->raise();
        groupBox_3->raise();
        groupBox_4->raise();
        groupBox_7->raise();
        groupBox_8->raise();
        groupBox_9->raise();
        groupBox_5->raise();
        groupBox_6->raise();
        groupBox_12 = new QGroupBox(tab);
        groupBox_12->setObjectName(QStringLiteral("groupBox_12"));
        groupBox_12->setGeometry(QRect(130, 20, 901, 451));
        groupBox_13 = new QGroupBox(groupBox_12);
        groupBox_13->setObjectName(QStringLiteral("groupBox_13"));
        groupBox_13->setGeometry(QRect(10, 0, 180, 130));
        label_food1_9 = new QLabel(groupBox_13);
        label_food1_9->setObjectName(QStringLiteral("label_food1_9"));
        label_food1_9->setGeometry(QRect(0, 0, 120, 80));
        label_food1_9->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/20001.jpg);"));
        label_desc_9 = new QLabel(groupBox_13);
        label_desc_9->setObjectName(QStringLiteral("label_desc_9"));
        label_desc_9->setGeometry(QRect(10, 90, 161, 16));
        label_desc_9->setFont(font4);
        label_value_9 = new QLabel(groupBox_13);
        label_value_9->setObjectName(QStringLiteral("label_value_9"));
        label_value_9->setGeometry(QRect(10, 110, 41, 16));
        label_value_9->setFont(font5);
        pushButton_get_10 = new QPushButton(groupBox_13);
        pushButton_get_10->setObjectName(QStringLiteral("pushButton_get_10"));
        pushButton_get_10->setGeometry(QRect(120, 20, 61, 41));
        pushButton_get_10->setCursor(QCursor(Qt::OpenHandCursor));
        pushButton_get_10->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/1.jpg);"));
        groupBox_14 = new QGroupBox(groupBox_12);
        groupBox_14->setObjectName(QStringLiteral("groupBox_14"));
        groupBox_14->setGeometry(QRect(230, 0, 180, 130));
        label_food1_10 = new QLabel(groupBox_14);
        label_food1_10->setObjectName(QStringLiteral("label_food1_10"));
        label_food1_10->setGeometry(QRect(0, 0, 120, 80));
        label_food1_10->setStyleSheet(QLatin1String("image: url(:/pic_tabBox/11S204/20002.jpg);\n"
""));
        label_desc_10 = new QLabel(groupBox_14);
        label_desc_10->setObjectName(QStringLiteral("label_desc_10"));
        label_desc_10->setGeometry(QRect(10, 90, 161, 16));
        label_desc_10->setFont(font4);
        label_value_10 = new QLabel(groupBox_14);
        label_value_10->setObjectName(QStringLiteral("label_value_10"));
        label_value_10->setGeometry(QRect(10, 110, 41, 16));
        label_value_10->setFont(font5);
        pushButton_get_11 = new QPushButton(groupBox_14);
        pushButton_get_11->setObjectName(QStringLiteral("pushButton_get_11"));
        pushButton_get_11->setGeometry(QRect(120, 20, 61, 41));
        pushButton_get_11->setCursor(QCursor(Qt::OpenHandCursor));
        pushButton_get_11->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/1.jpg);"));
        groupBox_15 = new QGroupBox(groupBox_12);
        groupBox_15->setObjectName(QStringLiteral("groupBox_15"));
        groupBox_15->setGeometry(QRect(10, 160, 180, 130));
        label_food1_11 = new QLabel(groupBox_15);
        label_food1_11->setObjectName(QStringLiteral("label_food1_11"));
        label_food1_11->setGeometry(QRect(0, 0, 120, 80));
        label_food1_11->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/20005.jpg);"));
        label_desc_11 = new QLabel(groupBox_15);
        label_desc_11->setObjectName(QStringLiteral("label_desc_11"));
        label_desc_11->setGeometry(QRect(10, 90, 161, 16));
        label_desc_11->setFont(font4);
        label_value_11 = new QLabel(groupBox_15);
        label_value_11->setObjectName(QStringLiteral("label_value_11"));
        label_value_11->setGeometry(QRect(10, 110, 41, 16));
        label_value_11->setFont(font5);
        pushButton_get_14 = new QPushButton(groupBox_15);
        pushButton_get_14->setObjectName(QStringLiteral("pushButton_get_14"));
        pushButton_get_14->setGeometry(QRect(120, 20, 61, 41));
        pushButton_get_14->setCursor(QCursor(Qt::OpenHandCursor));
        pushButton_get_14->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/1.jpg);"));
        groupBox_16 = new QGroupBox(groupBox_12);
        groupBox_16->setObjectName(QStringLiteral("groupBox_16"));
        groupBox_16->setGeometry(QRect(230, 160, 180, 130));
        label_food1_12 = new QLabel(groupBox_16);
        label_food1_12->setObjectName(QStringLiteral("label_food1_12"));
        label_food1_12->setGeometry(QRect(0, 0, 120, 80));
        label_food1_12->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/20006.jpg);"));
        label_desc_12 = new QLabel(groupBox_16);
        label_desc_12->setObjectName(QStringLiteral("label_desc_12"));
        label_desc_12->setGeometry(QRect(10, 90, 161, 16));
        label_desc_12->setFont(font4);
        label_value_12 = new QLabel(groupBox_16);
        label_value_12->setObjectName(QStringLiteral("label_value_12"));
        label_value_12->setGeometry(QRect(10, 110, 41, 16));
        label_value_12->setFont(font5);
        pushButton_get_15 = new QPushButton(groupBox_16);
        pushButton_get_15->setObjectName(QStringLiteral("pushButton_get_15"));
        pushButton_get_15->setGeometry(QRect(130, 20, 61, 41));
        pushButton_get_15->setCursor(QCursor(Qt::OpenHandCursor));
        pushButton_get_15->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/1.jpg);"));
        groupBox_17 = new QGroupBox(groupBox_12);
        groupBox_17->setObjectName(QStringLiteral("groupBox_17"));
        groupBox_17->setGeometry(QRect(450, 160, 180, 130));
        label_food1_13 = new QLabel(groupBox_17);
        label_food1_13->setObjectName(QStringLiteral("label_food1_13"));
        label_food1_13->setGeometry(QRect(0, 0, 120, 80));
        label_food1_13->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/20007.png);"));
        label_desc_13 = new QLabel(groupBox_17);
        label_desc_13->setObjectName(QStringLiteral("label_desc_13"));
        label_desc_13->setGeometry(QRect(10, 90, 161, 16));
        label_desc_13->setFont(font4);
        label_value_13 = new QLabel(groupBox_17);
        label_value_13->setObjectName(QStringLiteral("label_value_13"));
        label_value_13->setGeometry(QRect(10, 110, 41, 16));
        label_value_13->setFont(font5);
        pushButton_get_16 = new QPushButton(groupBox_17);
        pushButton_get_16->setObjectName(QStringLiteral("pushButton_get_16"));
        pushButton_get_16->setGeometry(QRect(120, 20, 61, 41));
        pushButton_get_16->setCursor(QCursor(Qt::OpenHandCursor));
        pushButton_get_16->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/1.jpg);"));
        groupBox_18 = new QGroupBox(groupBox_12);
        groupBox_18->setObjectName(QStringLiteral("groupBox_18"));
        groupBox_18->setGeometry(QRect(680, 160, 180, 130));
        label_food1_14 = new QLabel(groupBox_18);
        label_food1_14->setObjectName(QStringLiteral("label_food1_14"));
        label_food1_14->setGeometry(QRect(0, 0, 120, 80));
        label_food1_14->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/20008.jpg);"));
        label_desc_14 = new QLabel(groupBox_18);
        label_desc_14->setObjectName(QStringLiteral("label_desc_14"));
        label_desc_14->setGeometry(QRect(10, 90, 161, 16));
        label_desc_14->setFont(font4);
        label_value_14 = new QLabel(groupBox_18);
        label_value_14->setObjectName(QStringLiteral("label_value_14"));
        label_value_14->setGeometry(QRect(10, 110, 41, 16));
        label_value_14->setFont(font5);
        pushButton_get_17 = new QPushButton(groupBox_18);
        pushButton_get_17->setObjectName(QStringLiteral("pushButton_get_17"));
        pushButton_get_17->setGeometry(QRect(120, 20, 61, 41));
        pushButton_get_17->setCursor(QCursor(Qt::OpenHandCursor));
        pushButton_get_17->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/1.jpg);"));
        groupBox_19 = new QGroupBox(groupBox_12);
        groupBox_19->setObjectName(QStringLiteral("groupBox_19"));
        groupBox_19->setGeometry(QRect(450, 0, 180, 130));
        label_food1_15 = new QLabel(groupBox_19);
        label_food1_15->setObjectName(QStringLiteral("label_food1_15"));
        label_food1_15->setGeometry(QRect(0, 0, 120, 80));
        label_food1_15->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/20003.jpg);"));
        label_desc_15 = new QLabel(groupBox_19);
        label_desc_15->setObjectName(QStringLiteral("label_desc_15"));
        label_desc_15->setGeometry(QRect(10, 90, 161, 16));
        label_desc_15->setFont(font4);
        label_value_15 = new QLabel(groupBox_19);
        label_value_15->setObjectName(QStringLiteral("label_value_15"));
        label_value_15->setGeometry(QRect(10, 110, 41, 16));
        label_value_15->setFont(font5);
        pushButton_get_12 = new QPushButton(groupBox_19);
        pushButton_get_12->setObjectName(QStringLiteral("pushButton_get_12"));
        pushButton_get_12->setGeometry(QRect(120, 20, 61, 41));
        pushButton_get_12->setCursor(QCursor(Qt::OpenHandCursor));
        pushButton_get_12->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/1.jpg);"));
        groupBox_20 = new QGroupBox(groupBox_12);
        groupBox_20->setObjectName(QStringLiteral("groupBox_20"));
        groupBox_20->setGeometry(QRect(680, 0, 180, 130));
        label_food1_16 = new QLabel(groupBox_20);
        label_food1_16->setObjectName(QStringLiteral("label_food1_16"));
        label_food1_16->setGeometry(QRect(0, 0, 120, 80));
        label_food1_16->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/20004.jpg);"));
        label_desc_16 = new QLabel(groupBox_20);
        label_desc_16->setObjectName(QStringLiteral("label_desc_16"));
        label_desc_16->setGeometry(QRect(10, 90, 161, 16));
        label_desc_16->setFont(font4);
        label_value_16 = new QLabel(groupBox_20);
        label_value_16->setObjectName(QStringLiteral("label_value_16"));
        label_value_16->setGeometry(QRect(10, 110, 41, 16));
        label_value_16->setFont(font5);
        pushButton_get_13 = new QPushButton(groupBox_20);
        pushButton_get_13->setObjectName(QStringLiteral("pushButton_get_13"));
        pushButton_get_13->setGeometry(QRect(120, 20, 61, 41));
        pushButton_get_13->setCursor(QCursor(Qt::OpenHandCursor));
        pushButton_get_13->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/1.jpg);"));
        groupBox_21 = new QGroupBox(groupBox_12);
        groupBox_21->setObjectName(QStringLiteral("groupBox_21"));
        groupBox_21->setGeometry(QRect(10, 320, 180, 130));
        label_food1_17 = new QLabel(groupBox_21);
        label_food1_17->setObjectName(QStringLiteral("label_food1_17"));
        label_food1_17->setGeometry(QRect(0, 0, 120, 80));
        label_food1_17->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/20009.jpg);"));
        label_desc_17 = new QLabel(groupBox_21);
        label_desc_17->setObjectName(QStringLiteral("label_desc_17"));
        label_desc_17->setGeometry(QRect(10, 90, 161, 16));
        label_desc_17->setFont(font4);
        label_value_17 = new QLabel(groupBox_21);
        label_value_17->setObjectName(QStringLiteral("label_value_17"));
        label_value_17->setGeometry(QRect(10, 110, 41, 16));
        label_value_17->setFont(font5);
        pushButton_get_18 = new QPushButton(groupBox_21);
        pushButton_get_18->setObjectName(QStringLiteral("pushButton_get_18"));
        pushButton_get_18->setGeometry(QRect(120, 20, 61, 41));
        pushButton_get_18->setCursor(QCursor(Qt::OpenHandCursor));
        pushButton_get_18->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/1.jpg);"));
        groupBox_22 = new QGroupBox(groupBox_12);
        groupBox_22->setObjectName(QStringLiteral("groupBox_22"));
        groupBox_22->setGeometry(QRect(240, 320, 180, 130));
        label_food1_18 = new QLabel(groupBox_22);
        label_food1_18->setObjectName(QStringLiteral("label_food1_18"));
        label_food1_18->setGeometry(QRect(0, 0, 120, 80));
        label_food1_18->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/20010.jpg);"));
        label_desc_18 = new QLabel(groupBox_22);
        label_desc_18->setObjectName(QStringLiteral("label_desc_18"));
        label_desc_18->setGeometry(QRect(10, 90, 161, 16));
        label_desc_18->setFont(font4);
        label_value_18 = new QLabel(groupBox_22);
        label_value_18->setObjectName(QStringLiteral("label_value_18"));
        label_value_18->setGeometry(QRect(10, 110, 41, 16));
        label_value_18->setFont(font5);
        pushButton_get_19 = new QPushButton(groupBox_22);
        pushButton_get_19->setObjectName(QStringLiteral("pushButton_get_19"));
        pushButton_get_19->setGeometry(QRect(120, 20, 61, 41));
        pushButton_get_19->setCursor(QCursor(Qt::OpenHandCursor));
        pushButton_get_19->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/1.jpg);"));
        groupBox_23 = new QGroupBox(groupBox_12);
        groupBox_23->setObjectName(QStringLiteral("groupBox_23"));
        groupBox_23->setGeometry(QRect(450, 320, 180, 130));
        label_food1_20 = new QLabel(groupBox_23);
        label_food1_20->setObjectName(QStringLiteral("label_food1_20"));
        label_food1_20->setGeometry(QRect(0, 0, 120, 80));
        label_food1_20->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/20011.jpg);"));
        label_desc_20 = new QLabel(groupBox_23);
        label_desc_20->setObjectName(QStringLiteral("label_desc_20"));
        label_desc_20->setGeometry(QRect(10, 90, 161, 16));
        label_desc_20->setFont(font4);
        label_value_20 = new QLabel(groupBox_23);
        label_value_20->setObjectName(QStringLiteral("label_value_20"));
        label_value_20->setGeometry(QRect(10, 110, 41, 16));
        label_value_20->setFont(font5);
        pushButton_get_20 = new QPushButton(groupBox_23);
        pushButton_get_20->setObjectName(QStringLiteral("pushButton_get_20"));
        pushButton_get_20->setGeometry(QRect(130, 20, 61, 41));
        pushButton_get_20->setCursor(QCursor(Qt::OpenHandCursor));
        pushButton_get_20->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/1.jpg);"));
        groupBox_24 = new QGroupBox(groupBox_12);
        groupBox_24->setObjectName(QStringLiteral("groupBox_24"));
        groupBox_24->setGeometry(QRect(680, 320, 180, 130));
        label_food1_22 = new QLabel(groupBox_24);
        label_food1_22->setObjectName(QStringLiteral("label_food1_22"));
        label_food1_22->setGeometry(QRect(0, 0, 120, 80));
        label_food1_22->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/20012.jpg);"));
        label_desc_22 = new QLabel(groupBox_24);
        label_desc_22->setObjectName(QStringLiteral("label_desc_22"));
        label_desc_22->setGeometry(QRect(10, 90, 161, 16));
        label_desc_22->setFont(font4);
        label_value_22 = new QLabel(groupBox_24);
        label_value_22->setObjectName(QStringLiteral("label_value_22"));
        label_value_22->setGeometry(QRect(10, 110, 41, 16));
        label_value_22->setFont(font5);
        pushButton_get_21 = new QPushButton(groupBox_24);
        pushButton_get_21->setObjectName(QStringLiteral("pushButton_get_21"));
        pushButton_get_21->setGeometry(QRect(120, 20, 61, 41));
        pushButton_get_21->setCursor(QCursor(Qt::OpenHandCursor));
        pushButton_get_21->setStyleSheet(QStringLiteral("image: url(:/pic_tabBox/11S204/1.jpg);"));
        pushButton = new QPushButton(tab);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(10, 260, 111, 51));
        QFont font6;
        font6.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font6.setPointSize(11);
        font6.setBold(true);
        font6.setWeight(75);
        pushButton->setFont(font6);
        pushButton->setStyleSheet(QStringLiteral("border-image: url(:/pic_main/25.jpg);"));
        QIcon icon1;
        icon1.addFile(QStringLiteral(":/pic_tabBox/supermarke.png"), QSize(), QIcon::Normal, QIcon::Off);
        tabWidget_jxnu->addTab(tab, icon1, QString());
        tab_2 = new QWidget();
        tab_2->setObjectName(QStringLiteral("tab_2"));
        tabWidget_jxnu->addTab(tab_2, QString());
        groupBox_hold = new QGroupBox(groupBox_2);
        groupBox_hold->setObjectName(QStringLiteral("groupBox_hold"));
        groupBox_hold->setGeometry(QRect(1090, 310, 251, 251));
        label_hold = new QLabel(groupBox_hold);
        label_hold->setObjectName(QStringLiteral("label_hold"));
        label_hold->setGeometry(QRect(90, 40, 91, 31));
        QFont font7;
        font7.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font7.setPointSize(14);
        font7.setBold(true);
        font7.setWeight(75);
        label_hold->setFont(font7);
        pushButton_create = new QPushButton(groupBox_hold);
        pushButton_create->setObjectName(QStringLiteral("pushButton_create"));
        pushButton_create->setGeometry(QRect(30, 40, 201, 191));
        pushButton_create->setCursor(QCursor(Qt::PointingHandCursor));
        pushButton_create->setStyleSheet(QStringLiteral("image: url(:/pic_main/shop.png);"));
        pushButton_create->raise();
        label_hold->raise();
        pushButton_admin = new QPushButton(groupBox_2);
        pushButton_admin->setObjectName(QStringLiteral("pushButton_admin"));
        pushButton_admin->setGeometry(QRect(1000, 590, 201, 22));
        QFont font8;
        font8.setFamily(QString::fromUtf8("\345\256\213\344\275\223"));
        font8.setPointSize(12);
        font8.setBold(true);
        font8.setUnderline(false);
        font8.setWeight(75);
        pushButton_admin->setFont(font8);
        pushButton_admin->setStyleSheet(QStringLiteral(""));
        MainWindow->setCentralWidget(centralWidget);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);
        QWidget::setTabOrder(homeButton, user_Button);
        QWidget::setTabOrder(user_Button, collectionButton);
        QWidget::setTabOrder(collectionButton, messageButton);
        QWidget::setTabOrder(messageButton, textEdit);
        QWidget::setTabOrder(textEdit, jxnu_Button);
        QWidget::setTabOrder(jxnu_Button, ncgc_Button);
        QWidget::setTabOrder(ncgc_Button, dateTimeEdit);

        retranslateUi(MainWindow);

        toolBox->layout()->setSpacing(6);
        tabWidget_jxnu->setCurrentIndex(0);


        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", 0));
        groupBox->setTitle(QString());
        textEdit->setHtml(QApplication::translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:'SimSun'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"justify\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:48pt; font-weight:600; color:#000000;\">S-Store</span></p></body></html>", 0));
        homeButton->setText(QString());
        user_Button->setText(QString());
        collectionButton->setText(QString());
        messageButton->setText(QString());
        pushButton_recharge->setText(QApplication::translate("MainWindow", "\345\205\205\345\200\274", 0));
        label_message_2->setText(QApplication::translate("MainWindow", "\344\275\231\351\242\235", 0));
        label_money->setText(QApplication::translate("MainWindow", "TextLabel", 0));
        label_home->setText(QApplication::translate("MainWindow", "\351\246\226\351\241\265", 0));
        label_data->setText(QApplication::translate("MainWindow", "\344\270\252\344\272\272\350\265\204\346\226\231", 0));
        label_collection->setText(QApplication::translate("MainWindow", "\346\224\266\350\227\217\345\244\271", 0));
        label_message->setText(QApplication::translate("MainWindow", "\346\266\210\346\201\257", 0));
        groupBox_2->setTitle(QString());
        label_location->setText(QString());
#ifndef QT_NO_TOOLTIP
        page1->setToolTip(QApplication::translate("MainWindow", "<html><head/><body><p><br/></p></body></html>", 0));
#endif // QT_NO_TOOLTIP
#ifndef QT_NO_WHATSTHIS
        page1->setWhatsThis(QApplication::translate("MainWindow", "<html><head/><body><p><br/></p><p><br/></p></body></html>", 0));
#endif // QT_NO_WHATSTHIS
#ifndef QT_NO_ACCESSIBILITY
        page1->setAccessibleName(QString());
#endif // QT_NO_ACCESSIBILITY
        ncgc_Button->setText(QString());
        xian->setText(QString());
        xian_2->setText(QString());
        jxnu_Button->setText(QString());
        jxnu_Button_2->setText(QString());
        jxnu_Button_3->setText(QString());
        toolBox->setItemText(toolBox->indexOf(page1), QApplication::translate("MainWindow", "\345\215\227\346\230\214\345\234\260\345\214\272(\344\270\234\357\274\211", 0));
        toolBox->setItemText(toolBox->indexOf(page2), QString());
        toolBox->setItemText(toolBox->indexOf(page3), QString());
        toolBox->setItemText(toolBox->indexOf(page_back), QString());
#ifndef QT_NO_TOOLTIP
        tab->setToolTip(QString());
#endif // QT_NO_TOOLTIP
#ifndef QT_NO_STATUSTIP
        tab->setStatusTip(QApplication::translate("MainWindow", "S204\345\260\217\345\272\227", 0));
#endif // QT_NO_STATUSTIP
        xian_3->setText(QString());
        xian_4->setText(QString());
        xian_5->setText(QString());
        xian_6->setText(QString());
        label->setText(QString());
        pushButton_2->setText(QApplication::translate("MainWindow", "\346\226\271\344\276\277\351\200\237\351\243\237", 0));
        pushButton_3->setText(QApplication::translate("MainWindow", "\351\272\273\350\276\243\346\234\211\345\221\263", 0));
        pushButton_4->setText(QApplication::translate("MainWindow", "\344\274\221\351\227\262\351\243\237\345\223\201", 0));
        pushButton_5->setText(QApplication::translate("MainWindow", "\347\263\225\347\202\271\351\245\274\345\271\262", 0));
        pushButton_6->setText(QApplication::translate("MainWindow", "\351\245\256\346\226\231\351\205\222\346\260\264", 0));
        groupBox_11->setTitle(QString());
        groupBox_3->setTitle(QString());
        label_food1->setText(QString());
        label_desc->setText(QString());
        label_value->setText(QString());
        pushButton_get->setText(QString());
        groupBox_4->setTitle(QString());
        label_food1_2->setText(QString());
        label_desc_2->setText(QString());
        label_value_2->setText(QString());
        pushButton_get_2->setText(QString());
        groupBox_7->setTitle(QString());
        label_food1_5->setText(QString());
        label_desc_5->setText(QString());
        label_value_5->setText(QString());
        pushButton_get_5->setText(QString());
        groupBox_8->setTitle(QString());
        label_food1_6->setText(QString());
        label_desc_6->setText(QString());
        label_value_6->setText(QString());
        pushButton_get_6->setText(QString());
        pushButton_get_7->setText(QString());
        groupBox_9->setTitle(QString());
        label_food1_7->setText(QString());
        label_desc_7->setText(QString());
        label_value_7->setText(QString());
        pushButton_get_8->setText(QString());
        groupBox_10->setTitle(QString());
        label_food1_8->setText(QString());
        label_desc_8->setText(QString());
        label_value_8->setText(QString());
        pushButton_get_9->setText(QString());
        groupBox_5->setTitle(QString());
        label_food1_3->setText(QString());
        label_desc_3->setText(QString());
        label_value_3->setText(QString());
        pushButton_get_3->setText(QString());
        groupBox_6->setTitle(QString());
        label_food1_4->setText(QString());
        label_desc_4->setText(QString());
        label_value_4->setText(QString());
        pushButton_get_4->setText(QString());
        groupBox_12->setTitle(QString());
        groupBox_13->setTitle(QString());
        label_food1_9->setText(QString());
        label_desc_9->setText(QString());
        label_value_9->setText(QString());
        pushButton_get_10->setText(QString());
        groupBox_14->setTitle(QString());
        label_food1_10->setText(QString());
        label_desc_10->setText(QString());
        label_value_10->setText(QString());
        pushButton_get_11->setText(QString());
        groupBox_15->setTitle(QString());
        label_food1_11->setText(QString());
        label_desc_11->setText(QString());
        label_value_11->setText(QString());
        pushButton_get_14->setText(QString());
        groupBox_16->setTitle(QString());
        label_food1_12->setText(QString());
        label_desc_12->setText(QString());
        label_value_12->setText(QString());
        pushButton_get_15->setText(QString());
        groupBox_17->setTitle(QString());
        label_food1_13->setText(QString());
        label_desc_13->setText(QString());
        label_value_13->setText(QString());
        pushButton_get_16->setText(QString());
        groupBox_18->setTitle(QString());
        label_food1_14->setText(QString());
        label_desc_14->setText(QString());
        label_value_14->setText(QString());
        pushButton_get_17->setText(QString());
        groupBox_19->setTitle(QString());
        label_food1_15->setText(QString());
        label_desc_15->setText(QString());
        label_value_15->setText(QString());
        pushButton_get_12->setText(QString());
        groupBox_20->setTitle(QString());
        label_food1_16->setText(QString());
        label_desc_16->setText(QString());
        label_value_16->setText(QString());
        pushButton_get_13->setText(QString());
        groupBox_21->setTitle(QString());
        label_food1_17->setText(QString());
        label_desc_17->setText(QString());
        label_value_17->setText(QString());
        pushButton_get_18->setText(QString());
        groupBox_22->setTitle(QString());
        label_food1_18->setText(QString());
        label_desc_18->setText(QString());
        label_value_18->setText(QString());
        pushButton_get_19->setText(QString());
        groupBox_23->setTitle(QString());
        label_food1_20->setText(QString());
        label_desc_20->setText(QString());
        label_value_20->setText(QString());
        pushButton_get_20->setText(QString());
        groupBox_24->setTitle(QString());
        label_food1_22->setText(QString());
        label_desc_22->setText(QString());
        label_value_22->setText(QString());
        pushButton_get_21->setText(QString());
        pushButton->setText(QApplication::translate("MainWindow", "\345\205\266\345\256\203", 0));
        tabWidget_jxnu->setTabText(tabWidget_jxnu->indexOf(tab), QApplication::translate("MainWindow", "11#S204\345\260\217\345\272\227", 0));
        tabWidget_jxnu->setTabText(tabWidget_jxnu->indexOf(tab_2), QApplication::translate("MainWindow", "\343\200\202\343\200\202\346\213\233\347\247\237ing", 0));
        groupBox_hold->setTitle(QString());
        label_hold->setText(QApplication::translate("MainWindow", "\347\224\263\350\257\267\345\274\200\345\272\227", 0));
        pushButton_create->setText(QString());
        pushButton_admin->setText(QApplication::translate("MainWindow", "\347\256\241\347\220\206\345\221\230\347\256\241\347\220\206", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
